version: '3'
services:
  web:
    container_name: ${WEB_HOST}
    image: ${WEB_IMAGE_NAME}:${WEB_IMAGE_TAG}
    build: ./
    depends_on:
      - db
    ports:
      - "${WEB_PORT}:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
      - ./addons-customize:/mnt/extra-addons-customize
    entrypoint: "/usr/bin/odoo -c /etc/odoo/odoo.conf"
  db:
    container_name: ${DB_HOST}
    image: ${DB_IMAGE}:${DB_TAG}
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWD}
      - POSTGRES_USER=${DB_USER}
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    
  pgadmin:
    image: dpage/pgadmin4:4.25
    container_name: pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin
      PGADMIN_DEFAULT_PASSWORD: miclave
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
    links:
      - "db:pgsql-server"
volumes:
  odoo-db-data:
  odoo-web-data: